routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\EventController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\CouponController;



// Route::get('/', function () {
//     return view('welcome');
// });
// Auth::routes();
Route::get('/',[HomeController::class, 'index']);
Route::get('find-event',[HomeController::class, 'findEvent'])->name('findEvent');
Route::get('/login',[AuthController::class, 'showLogin'])->name('login');
Route::post('/login',[AuthController::class, 'login']);
Route::get('/register',[AuthController::class, 'showRegistration'])->name('register');
Route::post('/register',[AuthController::class, 'register']);
Route::post('/logout',[AuthController::class, 'logout'])->name('logout');
Route::view('/contact','contactUs')->name('contact');
Route::post('/contact-us',[HomeController::class, 'contacts'])->name('contactus');

Route::get('/category/view/{id}',[HomeController::class, 'cat_view'])->name('event-category');
Route::get('/event/detail/{id}',[HomeController::class, 'event_detail']);
Route::get('/booking/{id}',[HomeController::class, 'booking']);
Route::post('/booking-info',[HomeController::class, 'booking_info']);
Route::get('/checkout/{id}',[HomeController::class, 'checkout']);
Route::post('/checkout',[HomeController::class, 'checkout_info']);
Route::post('/search/events',[HomeController::class, 'catSearchEvents'])->name('cat-search-events');
Route::post('/all/search/events',[HomeController::class, 'allSearchEvents'])->name('search-events');
Route::get('/events/search',[HomeController::class, 'indexEventSearch'])->name('index.search');
Route::get('/orgnizer-details',[HomeController::class, 'test']);

Route::group(['middleware' => 'isLogin'], function(){
	Route::view('/dashboard','user.dashboard');
	
	// Event Routes
	// Route::get('/events',[EventController::class,'index'])->name('events');
	Route::resource('events', EventController::class);
	Route::view('event/create','user.events.create_new_event');
	Route::post('/store/event',[EventController::class,'store'])->name('create.event');
	// Sales Routes
	Route::get('sales/reports',[EventController::class,'sale'])->name('sales.report');
	Route::get('tickets/reports',[EventController::class,'ticket'])->name('ticket.report');

	Route::resource('coupons', CouponController::class);
	// Route::post('coupon/store',[CouponController::class,'store'])->name('coupons.store');
	
});

app/Models/Coupon.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Coupon extends Model
{
    use HasFactory;
    
    public function event()
    {
        return $this->belongsTo(Event::class);
    }
    
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/CouponController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Coupon;
use App\Models\Event;

class CouponController extends Controller
{
    public function index()
    {
        $coupons = Coupon::with(['event'])->get();
       // dd($coupons);
        $events = Event::all();
        return view('user.coupons.coupons', compact('coupons','events'));
    }
    
    public function store(Request $request)
    {//dd($request->all());
        $request->validate([
                'event_id' => 'required',
                'title' => 'required',
                'code' => 'required'
            ]);
            
        $data = new Coupon;
        $data->event_id = $request->event_id;
        $data->title = $request->title;
        $data->code = $request->code;
        $data->discount_type = $request->discount_type;
        $data->discount_amount = $request->discount_amount;
        $data->max_usage = $request->max_usage;
        $data->save();
        if($data)
        {
            return redirect()->back()->with('message','Coupon Has been inserted');
        }else{
            return redirect()->back()->with('err_message','Some problem occure please try again');
        }
    }

    public function destroy($id)
    {
        //dd($id);
        Coupon::destroy($id);
        return redirect('coupons');
    }   
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use App\Models\User;

class UserController extends Controller
{
    public function login(Request $request)
    {
        $request->validate([
            'email' => 'required|email|unique:users',
            'password' => 'required|min:5',
        ]);

        $email = $request->email;
        $password = Hash::make($request->password);
        $user = User::where('email',$email)->first();
        if($user && Hash::check($password, $user->password))
        {
            echo "good";
        }else{
            return redirect()->back()->with('message','Invalid Credentials');
        }

    }
}

resources/views/user/coupons/coupons.blade.php
@extends('layout.dashboard')
@section('content')
<!-- Sidebar -->
@include('includes.dashboard.sidebar')
<!-- navbar -->
@include('includes.dashboard.navbar')
<main id="main-container">
<!-- Hero -->
<div class="bg-body-light">
    <div class="content">
        <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
            <h1 class="flex-sm-fill h3 my-2">
            Coupon
            </h1>
        </div>
        <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
            <nav class="flex-sm-00-auto" aria-label="breadcrumb">
                <ol class="breadcrumb breadcrumb-alt">
                    <li class="breadcrumb-item">
                        <a class="link-fx" href="https://voagstech.com/sports/dashboard">Home</a>
                    </li>
                    <li class="breadcrumb-item active" aria-current="page">
                        Coupons
                    </li>
                </ol>
            </nav>
            
            <a href="#" data-toggle="modal" data-target="#createModal" class="btn btn-primary btn-add-new pull-right">
                <i class="fa fa-plus-square fa-lg"></i> Add New
            </a>
        </div>
        @if(Session::has('message'))
            <p class="alert alert-info">{{ Session::get('message') }}</p>
        @endif
    </div>
</div>
<!-- END Hero -->
<!-- Page Content -->
<div class="content">
    <div class="block block-rounded block-themed">
        <div class="block-content">
            
            <form method="post" role="form" id="data-search-form">
                <div class="table-responsive">
                    
                    <table class="table table-striped table-hover"  id="myDataTable">
                        <thead>
                            <tr role="row" class="heading">
                                <td>
                                    <input type="text" class="form-control" id="s_title" autocomplete="off" placeholder="Title">
                                </td>
                                
                                <td>&nbsp;</td>
                                <td>&nbsp;</td>
                            </tr>
                            <tr role="row" class="heading">
                                <th>Title</th>
                                <th>Event</th>
                                <th>Code</th>
                                <th>Discount Type</th>
                                <th>Discount</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse($coupons as $event)
                                <tr>
                                    <td>{{@$event->title}}</td>
                                    <td>{{@$event->event->title}}</td>
                                    <td>{{@$event->code}}</td>
                                    <td>{{@$event->discount_type}}</td>
                                    <td>{{@$event->discount_amount}}</td>
                                    <td>
                                                <div class="btn-group" role="group" aria-label="Horizontal Info">
                                                    <!-- <a class="btn btn-outline-primary" href="#" title="View Details">
                                            			<i class="fa fa-edit"></i>
                                            		</a>  -->
                                                    <a class="btn btn-outline-primary" href="javascript:;" onclick="confirmDelete('{{$event->id}}')">
                                            			<i class="fa fa-trash fa-lg text-danger btnRemove"></i>
                                            		</a>
                                                    
                                                            <form id="delete-blog-{{$event->id}}"
                                                                  action="{{ route('coupons.destroy', $event->id) }}"
                                                                  method="POST" style="display: none;">
                                                                @method('DELETE')
                                                                @csrf
                                                            </form>
                                                </div>
                                            </td>
                                </tr>
                            @empty
                            @endforelse
                        </tbody>
                    </table>
                </div>
            </form>
        </div>
    </div>
</div>
<!-- END Page Content -->

<div class="modal" id="createModal" tabindex="-1" role="dialog" aria-labelledby="createModal" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
    <div class="block block-rounded block-themed mb-0">
        <div class="block-header block-header-default">
            <h3 class="block-title">Add New</h3>
            <div class="block-options">
                <button type="button" class="btn-block-option btn_close_modal" data-bs-dismiss="modal" aria-label="Close">
                <i class="fa fa-fw fa-times"></i>
                </button>
            </div>
        </div>
        
        <form method="POST" action="{{route('coupons.store')}}">
        @csrf
        <div class="block-content fs-sm">
            <div class="row justify-content-center mt-2 mb-2 form-group">
                <div class="col-sm-12">
                    <div class="row">
                        <div class="col-sm-4">
                            <label for="event">Event</label>
                        </div>
                        <div class="col-sm-8">
                            <select class="form-control" name="event_id">
                                <option selected="selected" value="">select event</option>
                                @if($events)
                                    @foreach($events as $event)
                                        <option value="{{$event->id}}">{{$event->title}}</option>
                                    @endforeach
                                @endif
                            </select>
                        </div>
                    </div>
                    <div class="row mt-3">
                        <div class="col-sm-4">
                            <label for="title">Title</label>
                        </div>
                        <div class="col-sm-8">
                            <input class="form-control" name="title" type="text" id="title">
                        </div>
                    </div>
                    <div class="row mt-3">
                        <div class="col-sm-4">
                            <label for="code">Coupen Code</label>
                        </div>
                        <div class="col-sm-8">
                            <input class="form-control" name="code" type="text" id="code">
                        </div>
                    </div>
                    <div class="row mt-3">
                        <div class="col-sm-4">
                            <label for="discount_amount">Discount Type</label>
                        </div>
                        <div class="col-sm-8">
                            <div class="row">
                                <div class="col-sm-1">
                                    &nbsp;
                                </div>
                                <div class="col-sm-4 custom-control custom-radio custom-control-primary">
                                    <input type="radio" value="fixed" class="custom-control-input " id="fixed" name="discount_type">
                                    <label class="custom-control-label" for="fixed"><strong>Fixed</strong></label>
                                </div>
                                <div class="col-sm-5 custom-control custom-radio custom-control-primary">
                                    <input type="radio" value="percentege" class="custom-control-input " id="percentege" name="discount_type">
                                    <label class="custom-control-label" for="percentege"><strong>Percentege</strong></label>
                                </div>
                            </div>
                        </div>
                    </div><div class="row mt-3">
                    <div class="col-sm-4">
                        <label for="discount_amount">Discount Value</label>
                    </div>
                    <div class="col-sm-8">
                        <input class="form-control" name="discount_amount" type="text" id="discount_amount">
                    </div>
                </div>
                <div class="row mt-3">
                    <div class="col-sm-4">
                        <label for="max_usage">Set Limit:</label>
                    </div>
                    <div class="col-sm-8">
                        <input class="form-control" name="max_usage" type="number" id="max_usage">
                    </div>
                </div>
                <div class="row mt-3">
                    <div class="col-sm-4">
                    </div>
                    <div class="col-sm-8">
                        <input class="btn btn-primary" type="submit" value="Save">
                        <a href="" class="btn btn-outline-dark">Cancel</a>
                    </div>
                </div>
            </div>
        </div>
                        </div>
                        
                    </form>
                    
                </div>
            </div>
</div>
</div>

</main>
    <!-- Footer -->

        <footer id="page-footer" class="bg-body-light">

            <div class="content py-3">

                <div class="row font-size-sm">

                    <!-- <div class="col-sm-6 order-sm-2 py-1 text-center text-sm-right">

                        Crafted with <i class="fa fa-heart text-danger"></i>

                    </div> -->

                    <div class="  col-sm-12 order-sm-1 py-1 text-center  ">

                        &copy; <span data-toggle="year-copy"></span> <a class="font-w600" href="https://voagstech.com/sports/dashboard" target="_blank">Sports</a>

                    </div>

                </div>

            </div>

        </footer>

        <!-- END Footer -->
    @endsection
    @section('scripts')

    <script>
    jQuery(document).ready(function(e) {
        if(jQuery('.btn_close_modal'))
    	{
    		jQuery('.btn_close_modal').click(function(e) {
                $('#createModal').modal('hide');
            });
    	}
    });
    </script>
    <script>
        function confirmDelete(id) {
            let choice = confirm('Are you sure, You want to delete ?');
            if (choice) {
                document.getElementById('delete-blog-' + id).submit();
            }
        }
    </script>
    @endsection